### ISSUE TITLE
executable name change request

### ISSUE THREAD

**Issue by jimsalterjrs** [graham00/syncoid-rsync#1]
Hi @graham00! Thanks for publishing your work here.

To avoid confusion (and make it possible for people to potentially use both versions for different tasks), would you mind changing the name of your fork of the tool itself - ie, `git mv syncoid syncoid-rsync`?  Here's a quick tutorial on how to do it the right way: https://help.github.com/articles/renaming-a-file-using-the-command-line/

I was going to submit a pull request so you could just accept it, but it turned out to be unreasonably hard to fork your fork of my repo back to a different repo on my account, and I'm not git-github-wizardly enough to know how to try to offer a PR using just git alone without the web UI. =)

You might also consider creating a branch of this repo named syncoid-rsync, and changing that branch to be the default for your repo.  This would allow us to more easily submit PRs and fork back and forth with one another, without possibly screwing up the master for either version.

**Comment by graham00** [comment]
Hi Jim. Sure, will-do. There's a bit of hardcoding in a few places regarding the syncoid filename in the new functions. I'll clean that up so it detects whatever name it's running as instead, make sure that's working, then rename it here. I'll probably still leave it so it requires "--rsync" to use the new mode, in case people want to use the same copy to handle both modes.

I created a syncoid-rsync branch and made it the default. I'm not entirely clear what that does, but I'm okay with that :) Learning a bit of perl in the course of this has been fun, but github-ese is a language I only want to speak enough of to know it's not cursing at me :P

**Comment by jimsalterjrs** [comment]
I *think* it will make it possible for me to merge your syncoid-rsync branch into my own repo, which in turn will allow me to offer PRs to you directly rather than aimlessly suggest things. I found it entirely obnoxious that I couldn't just fork your fork into a new repo on my account... but apparently I can't!

I'm not sure it makes a ton of sense to force people to type "syncoid-rsync --rsync".  Hrm.  Perhaps it would make more sense to have a "--no-rsync" argument for if the user *doesn't* want to use the rsync features you've added?

**Comment by graham00** [comment]
Yeah, "syncoid-rsync --rsync" is a mouthful...

"--no-rsync" sounds sensible. I could add in some code to make the decision to not use the new mode if the source and destination are both local (currently it just aborts out with a warning), and that should work nicely.

**Comment by graham00** [comment]
Okay, I've got the changes made and tested. I'll commit them on here once I get your input on version/change tracking:

I was thinking about doing the following to add an increment to the version number:
`$version .= '.001';`

That way, as I make changes, they'll be reflected by a changed version number, but the base version number (ie, '1.X.XX') will still reflect the normal version of syncoid which the fork is based on. As you update syncoid, and I merge changes in, I can flip it back over to .001 ... ie:
`v 1.4.14.001 -> 1.4.14.002 -> 1.4.14.003 -> 1.4.15.001`

I could add change notes to the CHANGELIST in this fork.

Thoughts?

**Comment by jimsalterjrs** [comment]
I think the way Ubuntu numbers patches on packages probably makes more sense - it's a little easier to interpret.

Syncoid-rsync patch level 5 based on syncoid 1.4.14 would then look like syncoid-rsync 1.4.14-rsync5.

It's a little chewy, but at least it makes sense, right?

**Comment by graham00** [comment]
Yep, that sounds good. That's done, and I've updated changelist and the readme here. I renamed syncoid-rsync and updated the code.
